# https://docs.travis-ci.com/user/deployment/heroku/

language: dart
dart:
- stable

dart_task:

# As long as you don't want any other configuration, you can just use the name
# of a task instead of "name: true".
- test
- dartfmt

# Warnings are fatal, but we only analyze the lib/ directory.
- dartanalyzer: 

